src/Entity/ClTable.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Service\Functions;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TableRepository")
 */
class ClTable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Chapter", inversedBy="tables",fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $myChapter;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TableRow", mappedBy="myTable", orphanRemoval=true, cascade={"persist"},fetch="EXTRA_LAZY")
     */
    private $tableRows;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mainDescription;

    private $mainIndices;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $myNumber;

    public function __construct()
    {
        $this->tableRows = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id)
    {
        $this->id = $id;
    }

    public function getMyChapter(): ?Chapter
    {
        return $this->myChapter;
    }

    public function setMyChapter(?Chapter $myChapter): self
    {
        $this->myChapter = $myChapter;

        return $this;
    }

    /**
     * @return Collection|TableRow[]
     */
    public function getTableRows(): Collection
    {
        return $this->tableRows;
    }

    public function addTableRow(TableRow $tableRow): self
    {
        if (!$this->tableRows->contains($tableRow)) {
            $this->tableRows[] = $tableRow;
            $tableRow->setMyTable($this);
        }

        return $this;
    }

    public function removeTableRow(TableRow $tableRow): self
    {
        if ($this->tableRows->contains($tableRow)) {
            $this->tableRows->removeElement($tableRow);
            // set the owning side to null (unless already changed)
            if ($tableRow->getMyTable() === $this) {
                $tableRow->setMyTable(null);
            }
        }

        return $this;
    }

    public function getMainDescription(): ?string
    {
        return $this->mainDescription;
    }

    public function setMainDescription(string $mainDescription): self
    {
        $this->mainDescription = $mainDescription;

        return $this;
    } 
    public function getMainIndices(): ?string
    {
        return $this->mainIndices;
    }

    public function setMainIndices(string $mainIndices): self
    {
        $this->mainIndices = $mainIndices;

        return $this;
    } 
    public function SetAfterSplitLineIntoDescriptionAndIndices($line)
    {
        $slicePos = Functions::FindSlicePosition($line,'$',7);
        $this->mainDescription = trim(substr($line,0,$slicePos - 1));
        $this->mainIndices = substr($line,$slicePos,strlen($line)-1-$slicePos);
    }

    public function getMyNumber(): ?int
    {
        return $this->myNumber;
    }

    public function setMyNumber(?int $myNumber): self
    {
        $this->myNumber = $myNumber;

        return $this;
    }
    public function ExtractMyNumber(string $textLine)
    {
        return intval(substr(trim($textLine," *"),9));
    }
    public function getFullName()
    {
        // return sprintf("%02d",$this->myNumber);
        return $this->myChapter->getFullName().sprintf("%02d",$this->myNumber);
    }
    public function getDescription()
    {
        $arr = explode('$',$this->mainDescription);
        array_shift($arr);
        array_shift($arr);
        array_pop($arr);
        return implode('',$arr);
    }

    public function CreateDependecyForRenderAndTest($param)
    {
        $getIfexists = function($parmName) use($param)
        {
            return array_key_exists($parmName,$param) ? $param[$parmName] : null;
        };


        $this->myNumber = $getIfexists('ct_myNumber');
        $this->mainDescription = $getIfexists('mainDescription');

        $chapter = new Chapter;
        $cp_name = $getIfexists('cp_name');
        if ($cp_name != null)
        $chapter->setName($cp_name);
        $this->myChapter = $chapter;

        $catalog = new Catalog;
        $cat_name = $getIfexists('cat_name');
        if ($cat_name != null)
        $catalog->setName($cat_name);
        $chapter->setMyCatalog($catalog);

    }
}

src/Form/CatalogType.php
<?php

namespace App\Form;

use App\Entity\Catalog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CatalogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Catalog::class,
        ]);
    }
}

src/Controller/CatalogController.php
<?php

namespace App\Controller;

use App\Entity\Catalog;
use App\Entity\Kosztorys;
use App\Form\CatalogType;
use App\Repository\CatalogRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

require_once(__DIR__.'/../Service/Constants.php');

/**
 * @Route("/catalog")
 */
class CatalogController extends AbstractController
{
    /**
     * @Route("/", name="catalog_index", methods={"GET"})
     */
    public function index(CatalogRepository $catalogRepository): Response
    {
        
        return $this->render('catalog/index.html.twig', [
            'catalogs' => $catalogRepository->findAllByName(),
        ]);
    }
    /**
     * @Route("/kosztorys/{kosztorys}", name="catalog_index_przez_kosztorys", methods={"GET"})
     */
    public function indexPrzezKosztorys(CatalogRepository $catalogRepository, Kosztorys $kosztorys): Response
    {
        
        return $this->render('catalog/index.html.twig', [
            'catalogs' => $catalogRepository->findAllByName(),
            'kosztorys_id' => $kosztorys->getId(),
        ]);
    }
    
    /**
     * @Route("/indexAjax", name="catalog_indexAjax", methods={"GET", "POST"})
     */
    public function indexAjax(Request $request,CatalogRepository $catalogRepository): Response
    {
        $params = [];
        $params['catalogs'] = $catalogRepository->findByNameDescription($request->query->get("str"));
        $kId = $request->query->get("kosztorys_id");
        if($kId)$params['kosztorys_id'] = $kId;
        return $this->render('catalog/indexAjax.html.twig', $params);
        
    }

    /**
     * @Route("/indexAjaxDebug",name="catalog_indexAjax_debug", methods={"GET", "POST"})
     */
    public function indexAjaxDebug(Request $request,CatalogRepository $catalogRepository): Response
    {
        return $this->render('catalog/index.html.twig', [
            'catalogs' => $catalogRepository->findByNameDescription($request->query->get("str")),
            ]);
    }
    /**
     * @Route("/completeDescription", name="catalog_complete_description", methods={"GET"})
     */
    public function completeDescription(CatalogRepository $catalogRepository)
    {
        $catalogs = $catalogRepository->findAllIndexedByName();
        if(reset($catalogs)->getDescription() == null)
        {
            $catalogsWithDescrip = Catalog::LoadFrom(__DIR__.'/../../resources/Norma3/Kat/',CATALOG);
            $entityManager = $this->getDoctrine()->getManager();
            foreach($catalogsWithDescrip as $cdes)
            {
                $cdes->setId(0);
                $catalog = $catalogs[$cdes->getName()];
                $catalog->setDescription($cdes->getDescription());
                $entityManager->persist($catalog);
            }
            $entityManager->flush();
        }
        return $this->render('catalog/index.html.twig', [
            // 'catalogs' => $catalogsWithDescrip,
            'catalogs' => $catalogs,
        ]);
    }

    /**
     * @Route("/new", name="catalog_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $catalog = new Catalog();
        $form = $this->createForm(CatalogType::class, $catalog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($catalog);
            $entityManager->flush();

            return $this->redirectToRoute('catalog_index');
        }

        return $this->render('catalog/new.html.twig', [
            'catalog' => $catalog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="catalog_show", methods={"GET"})
     */
    public function show(Catalog $catalog): Response
    {
        return $this->render('catalog/show.html.twig', [
            'catalog' => $catalog,
        ]);
    }

    /**
     * @Route("/{id}/{kosztorys_id}", name="catalog_show_przez_kosztorys", methods={"GET"})
     */
    public function showPrzezKosztorys(Catalog $catalog,$kosztorys_id): Response
    {
        return $this->render('catalog/show.html.twig', [
            'catalog' => $catalog,
            'kosztorys_id' => $kosztorys_id,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="catalog_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Catalog $catalog): Response
    {
        $form = $this->createForm(CatalogType::class, $catalog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('catalog_index');
        }

        return $this->render('catalog/edit.html.twig', [
            'catalog' => $catalog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="catalog_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Catalog $catalog): Response
    {
        if ($this->isCsrfTokenValid('delete'.$catalog->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($catalog);
            $entityManager->flush();
        }

        return $this->redirectToRoute('catalog_index');
    }
}

templates/catalog/_delete_form.html.twig
<form method="post" action="{{ path('catalog_delete', {'id': catalog.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ catalog.id) }}">
    <button class="btn">Delete</button>
</form>

templates/catalog/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Catalog{% endblock %}

{% block body %}
    <h3>Edit Catalog</h3>

    {{ include('catalog/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('catalog_index') }}">back to list</a>

    {{ include('catalog/_delete_form.html.twig') }}
{% endblock %}

templates/catalog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalog index{% endblock %}

{% block scripts %}
        <script type="text/javascript" src="/js/findCatalog.js"></script>
{% endblock %}
{% block body %}
    <h3>Catalog index</h3>

    <div id="div_wyszukaj">
        wyszukaj
        <input id="input_find_catalog" type="tekst" placeholder="nazwa lub opis" size="30" 
        {% if kosztorys_id is defined %}
            kosztorys_id = "{{ kosztorys_id }}"
        {% endif %}
        
        >
    </div>
    <div id="kontener">kontener</div>
    {{ include('catalog/indexAjax.html.twig') }}

    

    <a href="{{ path('catalog_new') }}">Create new</a>
{% endblock %}

templates/catalog/indexAjax.html.twig
<table id="catalog_list" class="tableCatalogAjax">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
    {% for catalog in catalogs %}
        <tr>
            <td>{{ catalog.id }}</td>
            <td>{{ catalog.name }}</td>
            <td>
                {% if kosztorys_id is defined %}
                    <a href="{{ path('catalog_show_przez_kosztorys', {'id': catalog.id, 'kosztorys_id': kosztorys_id}) }}">
                {% else %}
                    <a href="{{ path('catalog_show', {'id': catalog.id}) }}">
                {% endif %}
                    {{ catalog.ShortenDescription(75) }}
                </a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="3">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/catalog/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Catalog{% endblock %}

{% block body %}
    <h3>Create new Catalog</h3>

    {{ include('catalog/_form.html.twig') }}

    <a href="{{ path('catalog_index') }}">back to list</a>
{% endblock %}

templates/catalog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalog{% endblock %}

{% block body %}
    <h3>{{ catalog.description }}</h3>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ catalog.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ catalog.name }}</td>
            </tr>
        </tbody>
    </table>
    <table>
        <thead>
            thead
        </thead>
        <tbody>
            {% for chap in catalog.myChapters %}
                <tr>
                    <td>
                        {% if kosztorys_id is defined %}
                            <a href="{{ path('chapter_show_przez_kosztorys', {'id': chap.id, 'kosztorys_id': kosztorys_id}) }}">
                        {% else %}
                            <a href="{{ path('chapter_show', {'id': chap.id}) }}">
                        {% endif %}
                            {{ chap.name}} {{ chap.description }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('catalog_index') }}">back to list</a>

    <a href="{{ path('catalog_edit', {'id': catalog.id}) }}">edit</a>

    {{ include('catalog/_delete_form.html.twig') }}
{% endblock %}